### ISSUE TITLE
v0.1.0 Release Roadmap

### ISSUE THREAD

**Issue by heltonmc** [JuliaMath/Bessels.jl#1]
## Float32
- [x] besselj0(x)
- [x] besselj1(x)
- [ ] besselj(nu, x)
- [x] bessely0(x)
- [x] bessely1(x)
- [ ] bessely(nu, x)
- [x] besseli(nu, x)
- [x] besseli0(x)
- [x] besseli0x(x)
- [x] besseli1(x)
- [x] besseli1x(x)
- [x] besselk(nu, x)
- [x] besselk0(x)
- [x] besselk0x(x)
- [x] besselk1(x)
- [x] besselk1x(x)

## Float64
- [x] besselj0(x)
- [x] besselj1(x)
- [x] besselj(nu, x)
- [x] bessely0(x)
- [x] bessely1(x)
- [x] bessely(nu, x)
- [x] besseli(nu, x)
- [x] besseli0(x)
- [x] besseli0x(x)
- [x] besseli1(x)
- [x] besseli1x(x)
- [x] besselk(nu, x)
- [x] besselk0(x)
- [x] besselk0x(x)
- [x] besselk1(x)
- [x] besselk1x(x)

**Comment by heltonmc** [comment]
I'm thinking it might be a good time for a 0.1.0 release soon once #29 gets merged and an update to the readme? 

We've now met all of these and a bit more with supporting any integer/noninteger order (pos or negative).

We might actually have a name conflict with `BesselK.jl`  though ....

**Comment by oscardssmith** [comment]
sounds great!

**Comment by cgeoga** [comment]
I also support a release. I can't wait to switch from using `SpecialFunctions` for the case `v isa AbstractFloat` to `Bessels.besselk`. 

I don't think there should be a name conflict though---`BesselK.jl` only exports `adbesselk` and `adbesselkxv`. If you export `besselk`, you would have a conflict with `SpecialFunctions.jl` though.

**Comment by oscardssmith** [comment]
I think that name conflict isn't a major problem. The solution is that SpecialFunctions in the future can make `SpecialFunctions.besselk` just re-export the Bessels.jl version.

**Comment by heltonmc** [comment]
Yes - I very much like that idea. I more so meant that `Bessels.jl` and `BesselK.jl` are too similar for the general registry to automatically merge, so will need a manual override I think.

Or we consider a name change of `Bessels.jl`.....

**Comment by cgeoga** [comment]
Oh wow, I didn't know that there were restrictions like that. I'm sorry for accidentally squatting on some valuable name real estate. It's hard to imagine anybody objecting to a manual override though. I suppose changing to, like, `BesselFunctions` wouldn't be insane either, but I would vote to try registering as-is and do the manual override. And apologies again for making this more complicated.

**Comment by heltonmc** [comment]
O not at all. Your package is aptly named but yes another option would be `BesselFunctions.jl`. I'm open for whatever is easier for the community on this.

I'd also be in support of moving this under the JuliaMath umbrella, but don't know that process.

**Comment by oscardssmith** [comment]
I think Bessels.jl is appropriate. It might be too similar for automerge, but we can just merge it manually.

**Comment by oscardssmith** [comment]
If you give me permissions to modify the settings of this repo, I think I can move it.

**Comment by heltonmc** [comment]
Hmmmm! I'm not for sure how to give you more permissions? I think you are already a collaborator but doesn't look like you can transfer to an org? Should I transfer the repo to you then you can move it? Might be easier if I could just transfer over to JuliaMath but I don't know who to get approval from there.

**Comment by oscardssmith** [comment]
I can give approval for the transfer.
