### ISSUE TITLE
Provide relative tolerances for besselj1(x) and besselj0(x) near zeros

### ISSUE THREAD

**Issue by heltonmc** [JuliaMath/Bessels.jl#22]
`besselj0(x)` and `besselj1(x)` are less accurate than in some cases compared to SpecialFunctions. It is necessary to have as high as accuracy as possible here to use in recurrence.

A particularly egregious example is...
```julia
julia> x = 36.917175397041404
36.917175397041404
julia> b = Bessels.besselj0
besselj0 (generic function with 3 methods)
julia> b = Bessels.besselj0(x)
1.011768220172076e-5
julia> s = SpecialFunctions.besselj0(BigFloat(x))
1.011768220171316454254168807990064731641395604156791812684039845214461189126123e-05
julia> (1 - s/b)/eps(Float64)
3380.747393649221098313930426393567621377521727019041833762438852447240038176093

#SpecialFunctions
julia> sf = SpecialFunctions.besselj0(x)
1.0117682201713196e-5
julia> (1 - s/sf)/eps(Float64)
13.84518197098556328359063545573609602974659455973659014095473715553658825833736
```

# besselj0 error
<img width="889" alt="Screen Shot 2022-05-19 at 11 23 05 AM" src="https://user-images.githubusercontent.com/57471570/169334848-d3e0b325-269e-407d-bbe7-0f9a2b74f1a0.png">

# besselj1 error
<img width="891" alt="Screen Shot 2022-05-19 at 11 24 14 AM" src="https://user-images.githubusercontent.com/57471570/169335277-f135adb0-caec-40ff-b47f-8edda124a27a.png">

**Comment by heltonmc** [comment]
It looks like this issue is limited to the asymptotic expansions for large arguments.

**Comment by heltonmc** [comment]
Hmmm well we can approximate their zeros fairly quickly....
```julia
x - pi/4 - evalpoly(x, (-1/8, 25/384, -1073/5120, 375733/229376, -55384775/2359296, 24713030909/46137344, -7780757249041/436207616)) = (m-1/2)*pi
```
Where `m` is some integer... will need some care though...

**Comment by heltonmc** [comment]
Looking at this a bit more. It is probably best to absorb the `pi/4` within the evaluation.

 This problem can then be reduced to simply computing
`(cos(x) * (cos(xn) + sin(xn)) + sin(x)*(cos(xn) - sin(xn)))` 
as accurately as possible.

An example close to a root is
```julia
(x, xn) = (46.341188371661815, -0.002696731212363751)
```
So then
```julia
julia> (cos(x) * (cos(xn) + sin(xn)) + sin(x)*(cos(xn) - sin(xn)))
-1.2212453270876722e-15
```

**Comment by heltonmc** [comment]
Or more simply we must calculate 
```julia
cos(x + xn) + sin(x + xn)
```
more accurately. Near roots `isapprox(abs(cos(x + xn)), abs(sin(x + xn)))` is true and we get some cancellation. We might want to check this condition then do the `cos(x + xn) + sin(x + xn)` with higher precision? Or have a better routine in general for that calculation.

**Comment by oscardssmith** [comment]
Isn't this just `sin(x + pi/4 + xn)`?

**Comment by heltonmc** [comment]
https://github.com/heltonmc/Bessels.jl/blob/ded7c2d1a401377df6752e5b4e2e0a2958f3974c/src/besselj.jl#L58-L63

So for our code replacing these lines with 
```julia
a = SQ2OPI(T) * sqrt(xinv) * p
xn = xinv * q
b = 0.7071067811865475 * (Float64(cos(BigFloat(x) + BigFloat(xn)) + sin(BigFloat(x) + BigFloat(xn))))
```
fixes this issue but obviously that's cheating 😄

**Comment by heltonmc** [comment]
This is improved by https://github.com/JuliaMath/Bessels.jl/pull/88. Which I think closes this issue.
