### ISSUE TITLE
Improving compile time of besselj and bessely

### ISSUE THREAD

**Issue by heltonmc** [JuliaMath/Bessels.jl#41]
I've noticed an increase in compile time for `besselj` and `bessely`
```julia
julia> tstart = time(); using Bessels; tend=time(); tend-tstart
[ Info: Precompiling Bessels [0e736298-9ec6-45e8-9647-e4fc86a2fe38]
0.7326688766479492

julia> tstart = time(); besselk(1.2, 8.2); tend=time(); tend-tstart
0.25269508361816406

julia> tstart = time(); besselj(1.2, 8.2); tend=time(); tend-tstart
1.9875857830047607

julia> tstart = time(); bessely(1.2, 8.2); tend=time(); tend-tstart
0.03860783576965332

julia> tstart = time(); besseli(1.2, 8.2); tend=time(); tend-tstart
0.12631797790527344
```

Loading the package and the calls to `besseli` and `besselk` are ok, however the calls to `bessely` and `besselj` have a noticeable compile time. The reason in this instance that `bessely` is faster is because it shares the majority of its code with `besselj` so the ordering of the call will matter.

This is probably from the asymptotics expansion for large argument in src/asymptotics.jl. I'll look into this some more.

```julia
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, westmere)
```

**Comment by heltonmc** [comment]
Ok almost half the time is spent on this function https://github.com/JuliaMath/Bessels.jl/blob/c8a6951f653363046eb469c51fc682ff07ceb365/src/asymptotics.jl#L194.

Avoiding that function completely reduces the time by almost half....
```julia
julia> tstart = time(); using Bessels; tend=time(); tend-tstart
[ Info: Precompiling Bessels [0e736298-9ec6-45e8-9647-e4fc86a2fe38]
0.7163481712341309

julia> tstart = time(); besselj(1.2, 8.2); tend=time(); tend-tstart
1.0615880489349365
```

**Comment by heltonmc** [comment]
Adding a precompile statement....

```julia
precompile(besselj, (Float64, Float64))
```
To the startup file does help first run a bit...
```julia
julia> tstart = time(); using Bessels; tend=time(); tend-tstart
[ Info: Precompiling Bessels [0e736298-9ec6-45e8-9647-e4fc86a2fe38]
1.0870921611785889

julia> tstart = time(); besselj(1.2, 8.2); tend=time(); tend-tstart
0.47586894035339355
```

It might be worth precompiling just one of these function because there is so much code reuse.

**Comment by devmotion** [comment]
> Ok almost half the time is spent on this function 

Maybe try to remove broadcasting? Generally, broadcasting puts quite some stress on the compiler and in that function it seems not necessary.

**Comment by heltonmc** [comment]
Yes!! I was actually just doing that which decreased it by about 20%. So will make this change asap. There's actually a long history about these coefficients because we know exactly how many coefficients we need to use depending on the arguments but making this dynamic on runtime created a lot of issues with varying length tuples. There's a bit of redundancy with how it's set up now (decided to use blocks of 10, 20, and 30 coefficients) but I think this structure could be improved.

It looks like with making these changes and adding a single precompilation statement we can get this well under a second without increasing the load time much.

**Comment by heltonmc** [comment]
Bisecting this a bit. Here was a comment https://github.com/JuliaMath/Bessels.jl/pull/20#issuecomment-1179610530 that probably introduced these runtimes and subsequent discussion on this...

**Comment by heltonmc** [comment]
Just want to update as we released `v0.2.1` of Bessels.jl. The times using `v1.8.0` of julia are now

```julia
(@v1.8) pkg> status Bessels
Status `~/.julia/environments/v1.8/Project.toml`
  [0e736298] Bessels v0.2.1

julia> tstart = time(); using Bessels; tend=time(); tend-tstart
0.009932994842529297

julia> tstart = time(); besselj(1.2, 8.2); tend=time(); tend-tstart
0.6227350234985352

julia> tstart = time(); bessely(1.2, 8.2); tend=time(); tend-tstart
0.019026994705200195
```

The using statement for `Bessels.jl` is much better now and the first call to `besselj` is now over 3x faster than `v0.2.0`.

And just to compare to `SpecialFunctions.jl`. Loading the package is much slower but of course the first call to `besselj` is much faster.

```julia
julia> tstart = time(); using SpecialFunctions; tend=time(); tend-tstart
0.10833907127380371

julia> tstart = time(); besselj(1.2, 8.2); tend=time(); tend-tstart
0.05970907211303711
```

**Comment by oscardssmith** [comment]
Have you read https://sciml.ai/news/2022/09/21/compile_time/?

**Comment by heltonmc** [comment]
Haha I'm literally going through that now and the slack thread which made me revisit this!!!

```julia
import SnoopPrecompile
SnoopPrecompile.@precompile_all_calls begin
  f(1.0,1.0)
  f(1,1)
  f(Int32(1),1)
  f(1.0,Int128(1))
end
end
```
Should we try doing blocks like this...? Is this the standard going forward you think?

**Comment by oscardssmith** [comment]
yes.

**Comment by heltonmc** [comment]
One thing I'm still a bit confused about is that most of this time seems to be spent on the LLVM code generation.

```julia
julia> using Bessels, SnoopCompile

julia> tinf = @snoopi_deep besselj(2.5, 5.0)
InferenceTimingNode: 0.441880/0.441880 on Core.Compiler.Timings.ROOT() with 0 direct children

julia> @show tinf
tinf = InferenceTimingNode: 0.441880/0.441880 on Core.Compiler.Timings.ROOT() with 0 direct children
InferenceTimingNode: 0.441880/0.441880 on Core.Compiler.Timings.ROOT() with 0 direct children
```
Am I interpreting this correctly that their really isn't any inference time here that could be precompiled away? It seems like the DiffEq had tons of inference time so that block was very helpful?

**Comment by oscardssmith** [comment]
ah, if we're all LLVM time, it won't help. I guess that makes sense since we are fully type stable.

**Comment by heltonmc** [comment]
Ok that makes sense why it didn't help much. I'm not for sure if there is anything too actionable right now on our end then.

I've kinda found that the compiler struggles with longer tuples (N > 20) so lines like this really slows down code generation https://github.com/JuliaMath/Bessels.jl/blob/372120a41803ca012f8439f8f013035848202eb9/src/asymptotics.jl#L208 

Maybe as better support for fixed size vectors/tuples happen this will improve....
