### ISSUE TITLE
Improve besselj accuracy for large arguments for orders -1, 0, 1

### ISSUE THREAD

**Issue by jwscook** [JuliaMath/Bessels.jl#56]
Related to #37, which gives examples for order 11 and argument 1e9.

It looks as though the large argument expansions for `besselj0` and `besselj1` are also inaccurate. I made a [gist](https://gist.github.com/jwscook/4712f7120870f32378f00e69781e604a) comparing the differences with SpecialFunctions.jl over a large range of orders and magnitude of argument.

The gist produces this figure indicating that the errors blow up for orders -1, 0 and 1 and arguments > 1e16.
[BesseljComparison.pdf](https://github.com/JuliaMath/Bessels.jl/files/9794495/BesseljComparison.pdf)

**Comment by heltonmc** [comment]
Very much thank you for this report!!!! And the details are so helpful.

@oscardssmith this looks related to `cos_sum` failing for large arguments. When you have time could you have a look at that function when `x>1e16`.
```julia
function cos_sum(x, xn)
    s = x + xn
    n, r = reduce_pi02_med(s)
    lo = r.lo - ((s - x) - xn)
    hi = r.hi + lo
    y = Base.Math.DoubleFloat64(hi, r.hi-hi+lo)
    n = n&3
    if n == 0
        return Base.Math.cos_kernel(y)
    elseif n == 1
        return -Base.Math.sin_kernel(y)
    elseif n == 2
        return -Base.Math.cos_kernel(y)
    else
        return Base.Math.sin_kernel(y)
    end
end

@inline function reduce_pi02_med(x::Float64)
    pio2_1 = 1.57079632673412561417e+00

    fn = round(x*(2/pi))
    r  = muladd(-fn, pio2_1, x)
    w  = fn * 6.07710050650619224932e-11
    y = r-w
    return unsafe_trunc(Int, fn), Base.Math.DoubleFloat64(y, (r-y)-w)
end
```

On a quick inspection..
```julia
julia> cos_sum(1e20, 1.2)
-3.5964366282318264e27

julia> cos(1e20 + 1.2)
0.7639704044417283
```

**Comment by heltonmc** [comment]
https://github.com/JuliaMath/Bessels.jl/pull/13#discussion_r808663523

Relevant discussion on where this was introduced. Sure enough as Oscar said as long as x<1e16. I’m sorry for this I should have had tests for very large inputs.

**Comment by jwscook** [comment]
Great! Such fast work  :)
