### ISSUE TITLE
mutating bessels! for sequence

### ISSUE THREAD

**Issue by judober** [JuliaMath/Bessels.jl#59]
First of all thanks for this nice package!

My FR:
I have a usecase were I repeatedly calculate bessels of a certain range for n. It would be nice if I would not have to alocate a vector a each iteration but instead could use an preallocated array and mutate it with some kind of `besselj!(out, n, x)`.
E.g.
```[julia]
result = Vector{Float64}(undef, 1000)
n = 0:999
for i = 1:10
   besselj!(result, n, i)
   do_stuf(result)
end
```

**Comment by heltonmc** [comment]
I originally was thinking about this in the implementation.... not sure why I didn't go that route. One thing to take note of is the comments on the discourse announcement (https://discourse.julialang.org/t/ann-bessels-jl-bessel-hankel-and-airy-functions/87941/10) and then my follow up comments. For very high performance applications you will be able to beat approaches like this by implementing the recurrence yourself. (though there is a much higher chance of something going wrong 😅) If you want to drop your full code I could maybe offer a bit more pointers on the best way to set that up.

However, I do agree with you that this should be needed as it is definitely the simplest for the user! Thank you for the issue!!

**Comment by judober** [comment]
I saw the comments already however this seems not worth the potential problems to implement this manually but thanks for your offer. I just noticed that using the vectorized version increased the speed tremendously but also increased the allocations slightly.

**Comment by heltonmc** [comment]
I tend to agree with you that the easier approach with just a bit of performance hit is sometimes warranted :smile: . Also if your `do_stuff(result)` is expensive then the bessel calls will be pretty cheap. One thing to note since you are summing over large orders and kinda small arguments. The majority of your bessel functions will just be zero.

Also, glad to hear that you were also seeing a speed increase in the vectorization. Though, if there is some kind of MWE of the increased allocations (please feel free to open a different issue) I would love to take a look at that as there shouldn't be a difference.

Anyway, I will work on this and hopefully get this merged soon.

**Comment by judober** [comment]
I think the added allocations are to be expected as it is basically replacing
```[julia]
n = 0:999
for i = 1:10
   for m in n
      do_stuf(besselj(m, i))
   end
end
```
However, I happily take them for the performance gain.

The `do_stoff(result)` is quite cheap as it only collects and slightly modifies the results. Is there an upper bound so that I can say for a particular `i` I only need to calculate up to `n_max` (or down to `n_min`) and all higher `n` will be zero?

One more sidenote: I actually only need every second `n`. But its still faster to calculate the complete range and only use half of them. I need negative `n` too (so its like ```n=-999:2:999```) but i can get them from the positive.

**Comment by heltonmc** [comment]
O ok sorry yes compared to replacing the scalar code it will allocate more. 

Yes - there is a method that checks for underflow `Bessels.besselj_underflow_check(nu, x)` but that will return `true` if it underflows. A very conservative estimate will be `100 + 1.01*x + 85*Base.Math._approx_cbrt(x)`. So for every `x` you can calculate `n_max` that will get up to the order where `besselj` returns 0.0. That should be much faster, just round up to the nearest integer and to `1:n_max` for each `x` argument. This is of course without any other context to the algorithm.

Definitely for negative orders get them from the positive values. Ya there is not going to be a faster way to get every second `n`....
